# Generated by Django 4.2.11 on 2024-03-20 18:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['workspace', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата выполнения')),
                ('clousing_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project', to='task.department', verbose_name='Подразделение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус проекта',
                'verbose_name_plural': 'Статусы проекта',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата выполнения')),
                ('clousing_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task', to='task.department', verbose_name='Подразделение')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_task', to='task.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задачи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Рабочее пространство',
                'verbose_name_plural': 'Рабочие пространства',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Workspace_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_workspace_members', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_workspace_members', to='task.workspace', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Участник пространства',
                'verbose_name_plural': 'Участники пространства',
                'ordering': ['workspace', 'user'],
            },
        ),
        migrations.CreateModel(
            name='User_Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_right', to='task.user_roles', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_right', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Права пользователя',
                'verbose_name_plural': 'Права пользователей',
                'ordering': ['user', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Unauthorized_Access_Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, verbose_name='Url')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытки несанкционированного доступа',
                'verbose_name_plural': 'Попытки несанкционированного доступа',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Task_New_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_messages', models.IntegerField(default=0, verbose_name='Кол-во новых сообщений')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_message', to='task.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_message', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Новые сообщения в задаче',
                'verbose_name_plural': 'Новые сообщения в задаче',
                'ordering': ['task', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Task_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task_members', to='task.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task_members', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник задачи',
                'verbose_name_plural': 'Участники задачи',
                'ordering': ['task', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Task_Finish_Date_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateTimeField(verbose_name='Плановая дата выполнения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task_finish_date_history', to='task.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task_finish_date_history', to=settings.AUTH_USER_MODEL, verbose_name='Установил')),
            ],
            options={
                'verbose_name': 'История изменения плановой даты выполнения',
                'verbose_name_plural': 'Истории изменения плановых дат выполнения',
                'ordering': ['task', 'user', 'finish_date'],
            },
        ),
        migrations.CreateModel(
            name='Task_Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_reply_task_dispute', models.IntegerField(blank=True, default=0, verbose_name='ID родительского сообщения')),
                ('content', models.TextField(blank=True, verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('in_reply_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_dispute_in_reply_user', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_dispute', to='task.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_dispute', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Обсуждение задачи',
                'verbose_name_plural': 'Обсуждение задач',
                'ordering': ['task', 'user'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task', to='task.task_status', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_task', to='task.workspace', verbose_name='Рабочее пространство'),
        ),
        migrations.CreateModel(
            name='Project_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project_members', to='task.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project_members', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
                'ordering': ['project', 'user'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project', to='task.project_status', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_project', to='task.workspace', verbose_name='Рабочее пространство'),
        ),
        migrations.AddField(
            model_name='department',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_department', to='task.workspace', verbose_name='Рабочее пространство'),
        ),
    ]
