# Generated by Django 4.2.11 on 2024-09-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMessageReaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_message_reader', to='task.taskdispute', verbose_name='Сообщение')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_message_reader', to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Прочитал сообщение',
                'verbose_name_plural': 'Прочитали сообщение',
                'db_table': 'task_message_readers',
                'ordering': ['message', 'reader'],
            },
        ),
    ]
