# Generated by Django 4.2.11 on 2025-07-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmessagereaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessagereaders',
            name='reading_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения'),
        ),
    ]
